preEntrega/urls.py
from django.contrib import admin
from django.urls import path
from pawPatrol.views import *
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),

    path("", inicio, name= "inicio"),
    
    path("heroes/", heroes, name= "heroes"),
    path("villanos/", villanos, name= "villanos"),
    path("vehiculos/", vehiculos, name= "vehiculos"),
    path("favorito/", tufavorito, name= "favorito"),
    path("favorito/formfav/", agregarFavorito, name= "formfav"),
    path("favorito/verheroe/", verheroe, name= "verheroe"),
    path("favorito/verheroe/editarheroe/<nombreHeroe>/", actualizarfav,name= "editarheroe"),
    path("favorito/verheroe/eliminarheroe/<nombreHeroe>/", eliminarfav,name= "eliminarheroe"),


    
    path("comencemos/", comencemos, name= "comencemos"),
    path("padre/", padre),
    path("padre/", padre),

    path("heroes/formheroe/", agregarHeroe, name= "formheroe"),
    path("villanos/formvillano/", agregarVillano, name= "formvillano"),
    path("vehiculos/formvehiculo/", agregarVehiculo, name= "formvehiculo"),

    path("vehiculos/vehiculossig/", vehiculodos, name= "vehiculodos"),
    path("heroes/heroessig/", heroesdos, name= "heroesdos"),
    path("heroes/heroessig/buscar", buscarheroe, name= "buscar"),
    path("villanos/", villanos, name= "villanos"),
    path("aboutme/", sobremi, name= "aboutme"),
    
    path("editarperfil/", editar_perfil, name= "editarperfil"),
    path("login/", log, name="login"),
    path("signup/", registrar, name="signup"),
    path("logout/", cerrar_sesion, name="logout"),
    path("editaravatar/", editar_avatar, name= "editaravatar"),



    path("resultados/", resultados),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pawPatrol/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class heroe(models.Model):

    nombre = models.CharField(max_length=40)
    habilidad = models.CharField(max_length=70)
    raza = models.CharField(max_length=40)
    vehiculo = models.CharField(max_length=40)

class villano(models.Model):
    nombre = models.CharField(max_length=40)
    raza = models.CharField(max_length=40)
    vehiculo = models.CharField(max_length=100)

class vehiculo(models.Model):
    modelo = models.CharField(max_length= 40)
    propietario = models.CharField(max_length= 40)

class avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE) #un usuario ya creado
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)
    def __str__(self):
        return f"{self.usuario}-----{self.imagen}"

class favorito(models.Model):
    nombre = models.CharField(max_length=40)
    habilidad = models.CharField(max_length=70)
    raza = models.CharField(max_length=40)
    descripcion = models.CharField(max_length=300)

pawPatrol/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from pawPatrol.models import *

class formularioHeroes(forms.Form):
    nombre = forms.CharField(max_length=40)
    habilidad = forms.CharField(max_length=70)
    raza = forms.CharField(max_length=40)
    vehiculo = forms.CharField(max_length=40)

class formularioVillano(forms.Form):
    nombre = forms.CharField()
    raza = forms.CharField()
    vehiculo = forms.CharField()

class formularioVehiculo(forms.Form):
    modelo= forms.CharField(max_length= 40)
    propietario = forms.CharField(max_length= 40)

class formularioFavorito(forms.Form):
    nombre = forms.CharField(max_length=40)
    habilidad = forms.CharField(max_length=70)
    raza = forms.CharField(max_length=40)
    descripcion = forms.CharField(max_length=300)
            

class registro(UserCreationForm):
    username = forms.CharField(label="Ingrese su username")
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Ingrese la contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirme la contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Ingrese su nombre")
    last_name = forms.CharField(label="Ingrese su apellido")

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2", "first_name", "last_name"]

class editar(UserCreationForm):
    email = forms.EmailField(label="Email")
    password1 = forms.CharField(label="Ingrese la contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirme la contraseña", widget=forms.PasswordInput)
    first_name = forms.CharField(label="Ingrese su nombre")
    last_name = forms.CharField(label="Ingrese su apellido")

    class Meta:
        model = User
        fields = ["email", "password1", "password2", "first_name", "last_name"]

class editarAvatar(forms.ModelForm):

    class Meta:
        model = avatar
        fields = ["imagen"]

pawPatrol/views.py
from django.shortcuts import render, redirect
import random
from pawPatrol.models import *
from pawPatrol.forms import *
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.decorators import login_required

# Create your views here.

def inicio(request):

    return render(request, "inicio.html")

def villanos(request):
    return render(request, "villanos.html")

def vehiculos(request):
    return render(request, "vehiculos.html")

def comencemos(request):
    return render(request, "comencemos.html")

def padre(request):
    return render(request, "padre.html")

def heroes(request):
    return render(request, "heroes.html")
@login_required
def tufavorito(request):
    return render(request, "favorito.html")

@login_required
def agregarFavorito(request):
    if request.method == "POST":
        formfav = formularioFavorito(request.POST) #obtiene los datos
        if formfav.is_valid():
            info = formfav.cleaned_data #para tenerlo en modo diccionario
            formfav = favorito( nombre=info["nombre"], habilidad= info["habilidad"], raza=info["raza"],
                                descripcion = info["descripcion"])
            formfav.save()
            return redirect("favorito")
    else:
        formfav = formularioFavorito()

    return render(request, "formfav.html", {"nuevofav":formfav})

@login_required
def verheroe(request):      
    favoritos = favorito.objects.all()
    contexto = {"favoritos": favoritos}
    return render(request, "verheroe.html", contexto)

@login_required
def actualizarfav(request, nombreHeroe):

        upheroe = favorito.objects.get(nombre = nombreHeroe)
        
        if request.method == "POST":
            formu= formularioFavorito(request.POST)
            if formu.is_valid():
                info = formu.cleaned_data
                upheroe.nombre= info["nombre"]
                upheroe.raza= info["raza"]
                upheroe.habilidad= info["habilidad"]
                upheroe.descripcion= info["descripcion"]

                upheroe.save()

                return redirect("favorito")

        else:
            formu = formularioFavorito(initial={"nombre":upheroe.nombre, "raza":upheroe.raza,
                                                "habilidad": upheroe.habilidad, "descripcion": upheroe.descripcion})

        return render(request, "editarheroe.html", {"formu":formu, "nombre":nombreHeroe})        

@login_required
def eliminarfav(request, nombreHeroe):  
        delheroe = favorito.objects.get(nombre = nombreHeroe)
        delheroe.delete()

        heroes = favorito.objects.all()

        return redirect("favorito")

@login_required
def agregarHeroe(request):
    
    if request.method == "POST":
        nuevo_form = formularioHeroes(request.POST) #obtiene los datos
        if nuevo_form.is_valid():
            info = nuevo_form.cleaned_data #para tenerlo en modo diccionario
            nuevoHeroe = heroe(nombre=info["nombre"], raza=info["raza"], 
                               habilidad=info["habilidad"], vehiculo=info["vehiculo"])
            nuevoHeroe.save()
            return redirect("heroes")
    else:
        nuevo_form = formularioHeroes()

    return render(request, "formheroe.html", {"nuevoheroe":nuevo_form})


@login_required
def agregarVillano(request):
    if request.method == "POST":
        formVillano = formularioVillano(request.POST) #obtiene los datos
        if formVillano.is_valid():
            info = formVillano.cleaned_data #para tenerlo en modo diccionario
            formVillano = villano(nombre=info["nombre"],raza=info["raza"], vehiculo = info["vehiculo"])
            formVillano.save()
            return redirect("villanos")

    else:
        formVillano = formularioVillano()

    return render(request, "formvillano.html", {"nuevovillano":formVillano})

@login_required
def agregarVehiculo(request):
    
    if request.method == "POST":
        formVehiculo = formularioVehiculo(request.POST) #obtiene los datos
        if formVehiculo.is_valid():
            info = formVehiculo.cleaned_data #para tenerlo en modo diccionario
            nuevoVehiculo = vehiculo(modelo=info["modelo"],propietario=info["propietario"])
            nuevoVehiculo.save()
            return redirect("vehiculos")
    else:
        formVehiculo = formularioVehiculo()

    return render(request, "formvehiculo.html", {"nuevovehiculo":formVehiculo})


def heroesdos(request):

    return render(request, "heroessig.html")

def vehiculodos(request):

    return render(request, "vehiculossig.html")


def buscarheroe(request):
    return render(request, "buscarheroe.html")

def resultados(request):
    if request.method == "GET":

        pedido = request.GET["nombre"]
        resultado = heroe.objects.filter(nombre__icontains=pedido)

        return render(request, "resultados.html", {"nombre":resultado})
    else:
        respuesta= "No existen datos"
        return HttpResponse(respuesta)
 

def log(request):

    if request.method == "POST":
        form = AuthenticationForm(request, data = request.POST)
        if form.is_valid():
            
            info = form.cleaned_data

            usuario = info["username"]
            contraseña = info["password"]    

            user = authenticate(username=usuario, password=contraseña)

            if user is not None:
                login(request, user)

                return redirect("inicio")
            else:
                return render(request, "inicio.html", {"msj":f"Datos incorrectos"})

        else:
            return render(request, "inicio.html", {"msj":f"Formuario erroneo"})


    formulario= AuthenticationForm()
    
    return render(request, "registro/login.html", {"form":formulario})

def registrar(request):
    
    if request.method == "POST":
        form= registro(request.POST)

        if form.is_valid():
            
            info = form.cleaned_data

            usuario= info["username"]

            form.save()

            return redirect("inicio")
    else:
        form = registro()

    return render(request, "registro/registrar.html", {"form":form}) 

def cerrar_sesion(request):

    logout(request)

    return render(request, "registro/logout.html", {"msj": f"Has cerrado sesión"}) 

@login_required
def editar_perfil(request):
    usuario =  request.user
    if request.method == "POST":
        if request.method == "POST":
            form = editar(request.POST)

            if form.is_valid():
                
                info = form.cleaned_data
    
                usuario.first_name= info["first_name"]
                usuario.last_name= info["larst_name"]
                usuario.email= info["email"]
                usuario.set_password= info["password1"]

                usuario.save()
                return render(request, "inicio.html")
    else:
         form= editar(initial={"first_name": usuario.first_name,
                               "last_name": usuario.last_name,
                               "email": usuario.email})

    return render(request, "registro/editarUsuario.html", {"form":form})

@login_required
def editar_avatar(request):
    if request.method == "POST":
        formu = editarAvatar(request.POST, request.FILES)

        if formu.is_valid():

            info = formu.cleaned_data

            imagen = avatar(usuario= request.user , imagen= info["imagen"])

            imagen.save()

            return redirect("inicio")
    else:
        formu = editarAvatar()

    return render(request, "registro/editarAvatar.html", {"formu": formu})

def sobremi(request):

    return render(request, "aboutme.html")

pawPatrol/templates/aboutme.html
{%extends "padre.html" %}
{%block titulo%} Sobre mi {%endblock%}

{%block imagenes%}
<img src="https://scontent.fvlg2-1.fna.fbcdn.net/v/t1.6435-9/128066238_4220580214625276_7221522339523206365_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=7a1959&_nc_eui2=AeF16KObBk3hljIN7owUWcR_ImJRBfPA8lMiYlEF88DyU1vSI7yMKrwNLYaEfZo19KWK1zVnfjq2Z7VtKOjpYJeK&_nc_ohc=aeyapRz_UhcAX-jWiWI&_nc_ht=scontent.fvlg2-1.fna&oh=00_AfDq22E2zeLz1qLIGSWH-Rc2nfRc-99TF17WYJED_bQ79g&oe=65DD3025" width="450" alt="no anda">

{%endblock%}



{%block texto%}

    <style>
        .posicion-especifica-texto {
            position: absolute;
            top: 800px;
            left:550px;
            right: 100px;
        }
    </style>

<body>
    <div class="posicion-especifica-texto">
       <p> Hola y bienvenidos! mi nombre es Belén Signes, soy estudiante de computación y tia, esta pagina esta hecha para un proyecto final de mi curso, en parte. Tambien es una pagina que le hacia ilusion a mi sobrina, Francesca, fanatica de Paw Patrol.
        Siempre jugamos con estos personajes y nos divertimos creando nuevos. Por eso cuando me llego la propuesta fue en lo primero que pense. Para los curiosos ella fue codiseñadora de la pagina y esta muy contenta con los primeros resultado, espero que tambien lo este cuando la vea terminada por completo.
        Ademas, soy desarrolladora jr, aun me queda mucho que apreder pero me alegro que formen parte de mi primer proyecto.</p>
       <p> Gracias por visitar y si estan en problemas solo aulla por ayuda!!!
    </p>
    </div>
</body>

{%endblock%}

pawPatrol/templates/buscarheroe.html
{%extends "padre.html" %}
{%block titulo%} 
Ahora que ya los conoces, buscalos por su nombre y averigua mas datos sobre nuestros amigos 
<h2>Tambien puedes buscar tu cachorro personalizado.</h2>

<form action="/resultados/" method="GET">
    <input type="text" name="nombre">
    <input type="submit" value="Buscar">
</form>
{%endblock%}

pawPatrol/templates/comencemos.html
{%extends "padre.html" %} 
{%block navegacion%} {%endblock%}
{%block titulo%} ¿Por donde quieres empezar? {%endblock%}

{%block botones%} 
<a class="btn btn-primary" href="{%url 'heroes'%}">Heroes</a> 
<a class="btn btn-primary" href="{%url 'villanos'%}">Villanos</a> 
<a class="btn btn-primary" href="{%url 'vehiculos'%}">Vehiculos</a> 

{%endblock%}

pawPatrol/templates/editarheroe.html
{%extends "padre.html" %}

{%block formulario%}
<form action="" method="POST"> {%csrf_token%}
    
    {{formu.as_p}}

    <input type= "submit" , value="Actualizar">
</form>
{%endblock%}

pawPatrol/templates/favorito.html
{%extends "padre.html" %}
{%block titulo%}Hay muchos personajes mas en Bahia Aventura, contanos cual es el tuyo! {%endblock%}

{%block botones%} 
<a class="btn btn-primary" href="formfav">Sube el tuyo!</a>
<a class="btn btn-primary" href="verheroe">Ver mis heroes</a>

{%endblock%}

pawPatrol/templates/formheroe.html
{%extends "padre.html" %}
{%block titulo%} Personaliza tu heroe {%endblock%}


{%block formulario%}

<form action="" method="POST"> {%csrf_token%}
    
    {{nuevoheroe.as_p}}

    <input type= "submit" , value="Enviar">
</form>

{%endblock%}

pawPatrol/templates/formvillano.html
{%extends "padre.html" %}
{%block titulo%} Personaliza tu Villano {%endblock%}


{%block formulario%}

<form action="" method="POST"> {%csrf_token%}
    
    {{nuevovillano.as_p}}

    <input type= "submit" , value="Enviar">
</form>

{%endblock%}

pawPatrol/templates/imagenes.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Texto al Lado de una Imagen</title>
    <style>
        /* Estilo opcional para alinear la imagen y el texto */
        .contenedor-imagen {
            display: flex;
            align-items: center;
        }

        .contenedor-imagen img {
            margin-right: 10px; /* Espacio entre la imagen y el texto */
        }
    </style>
</head>
<body>

<!-- Contenedor que incluye una imagen y un párrafo de texto -->
<div class="contenedor-imagen">
    <p><img src="https://www.pngall.com/wp-content/uploads/13/Paw-Patrol-Transparent.png" 
    alt="Chase", width="180" class="imagen-chase"> </p>
    <p>Texto al lado de la imagen. Puedes agregar más texto aquí.</p>
</div>

</body>
</html>7





{%block texto%}

    <style>
        .posicion-especifica-zuma {
            position: absolute;
            top: 1150px;
            left: 300px;
        }
    </style>

<body>
    <div class="posicion-especifica-zuma">
       <p>Chase es un perrito policía, espía, por lo que sus deberes se enfocan en proteger a los ciudadanos,
         controlar el tránsito y buscar objetos perdidos. </p>
    </div>
</body>

<style>
    .posicion-especifica-rocky {
        position: absolute;
        top: 1400px;
        left: 50px;
    }
</style>

<body>
<div class="posicion-especifica-rocky">
   <p>Skye ama volar y ademas pose un helicoptero, por lo que sus deberes se enfocan en sobrevolar el aire,
     además</p><p>su vehículo tiene un gancho que le permite agarrar cosas.</p>
</div>
</body>

<style>
    .posicion-especifica-rubble {
        position: absolute;
        top: 1650px;
        left: 350px;
    }
</style>

<body>
<div class="posicion-especifica-rubble">
   <p>Marshall desempeña el papel de bombero, así como de cachorro médico, por lo que sus deberes se enfocan en sanar heridos,
        apagar incendios, rescatar a personas de sitios elevados </p>
</div>
</body>

<style>
    .posicion-especifica-rayder {
        position: absolute;
        top: 1650px;
        left: 350px;
    }
</style>

<body>
<div class="posicion-especifica-rayder">
   <p>Marshall desempeña el papel de bombero, así como de cachorro médico, por lo que sus deberes se enfocan en sanar heridos,
        apagar incendios, rescatar a personas de sitios elevados </p>
</div>
</body>
{%endblock%}


{%block siguiente%}
<style>
    /* Estilo CSS para posicionar el botón */
    .boton-al-final {
        position: absolute;
        top: 1850px;
        left: 675px;
        background-color: #1900ff;
        color: white;
        padding: 10px 20px;
        border: none;
        border-radius: 5px;
        cursor: pointer;
    }
</style>

<a class="boton-al-final" href="heroessig"> Descubre mas!!! </a>
{%endblock%}

https://www.pngall.com/wp-content/uploads/13/Paw-Patrol.png ray


https://i.pinimg.com/564x/5e/1a/1a/5e1a1a3ae4bd3fd6ae2dc498c19f5b1c.jpg rock

https://static.wikia.nocookie.net/paw-patrol/images/5/59/Zuma_PNG.png/revision/latest?cb=20190121213838&path-prefix=es zuma


{%block texto%}

    <style>
        .posicion-especifica-zumaV {
            position: absolute;
            top: 1150px;
            left: 300px;
        }
    </style>

<body>
    <div class="posicion-especifica-zumaV">
       <p> Zuma tiene un aerodeslizador naranja. Zuma puede disparar 
        anillos salvavidas desde el aerodeslizador. También puede transformarse en submarino </p>
    </div>
</body>

<style>
    .posicion-especifica-rockyV {
        position: absolute;
        top: 1400px;
        left: 50px;
    }
</style>

<body>
<div class="posicion-especifica-rockyV">
   <p>Rocky tiene un camión de reciclaje ecológico. Allí almacena piezas viejas que
     pueden usarse más adelante. También puede transformarse en remolcador.</p>
</div>
</body>

<style>
    .posicion-especifica-rubbleV {
        position: absolute;
        top: 1650px;
        left: 350px;
    }
</style>

<body>
<div class="posicion-especifica-rubbleV">
    <p>Rubble tiene una topadora amarilla. En la parte trasera hay un brazo perforador y 
        también una pala para excavadora </p>
</div>
</body>

<style>
    .posicion-especifica-rayderV {
        position: absolute;
        top: 1900px;
        left: 25px;
        
    }
</style>

<body>
<div class="posicion-especifica-rayderV">
   <p>Ryder tiene un vehículo todo terreno rojo que se transforma en una moto de agua y una moto de nieve.
     La transformación del vehículo está controlada por su Pup-Pad. Si presiona un botón, 
     puede desplegar un chaleco salvavidas antes de navegar hacia la bahía. </p>
</div>
</body>

{%endblock%}



<form action="/heroes/" method="POST" name="formPersonaliza"> {%csrf_token%}
    <p>Nombre <input type="text" name="nombre"> </p>
       
       </label for="habilidad"> Elige su habilidad </label>
       <select name="habilidad">
           <option>Astronauta</option>
           <option>Programador</option>
           <option>Cocinero</option>
           <option>Bibliotecario</option>
           <option>Doctor</option>
       </select>
   
       <p></label for="raza"> Elige su raza </label>
           <select name="raza">
            <option>Mestizo</option>
            <option>Beagle</option>
            <option>West Highland Terrier</option>
            <option>Labrador</option>
           </select>
       </p>
   
    <p>Vehiculo <input type="text" name="vehiculo"> </p>
   
       <input type= "submit" , value="Enviar">
   
   
   </form>
  
   


   def personalizarHeroe(request):
    
    if request.method == "POST":
        if request.method=="POST":
            numero = (random.randint(10, 10000))
            nuevoHeroe = heroe (id = numero ,nombre = request.POST["nombre"],
                            habilidad = request.POST["habilidad"], raza = request.POST["raza"],
                             vehiculo = request.POST["vehiculo"])
            nuevoHeroe.save()
            return render(request, "tupersonaje.html")
    else:
        nuevo_form = formularioHeroes()

    return render(request, "formheroe.html")

pawPatrol/templates/padre.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Paw Patrol</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Bootstrap icons-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" type="text/css" />
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'PawPatrol/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Navigation-->{%block navegacion%}
        <nav class="navbar navbar-light bg-light static-top">
            <div class="container">
                <a class="navbar-brand" href="{%url 'inicio'%}">Paw Patrol</a>
                {%if user.is_authenticated %}
                Hola {{user}}
               <button> <a href="editarperfil" title="Editar perfil" ><h9> Editar perfil</h9> <img src="{{user.avatar_set.last.imagen.url}}" alt="" width="70">  </a> </button>
               <a class="btn btn-primary" href="{%url 'favorito'%}">Tu favorito</a>
               <a class="btn btn-primary" href="{%url 'logout'%}">Cerrar Sesión</a>
                {%else%}
                <a class="btn btn-primary" href="{%url 'login'%}">Iniciar Sesión</a>
                <a class="btn btn-primary" href="{%url 'signup'%}">Registrarse</a>
                {%endif%}
            </div>
        </nav>
        {%endblock%}
        <!-- Masthead-->
        <header class="masthead">
            <div class="container position-relative">
                <div class="row justify-content-center">
                    <div class="col-xl-6">
                        <div class="text-center text-white">
                            <!-- Page heading-->
                            <h1 class="mb-5"> {%block titulo%} {%endblock%}</h1>

                            <!-- formulario-->
                            {%block formulario%} {%endblock%}
                            
                            <!-- buscar-->
                            {%block buscar%} {%endblock%}


                            <!-- parrafo-->
                            {%block parrafo%}{%endblock%}
                            <!-- boton-->
                            {%block botones%}  {%endblock%}

                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- * * SB Forms Contact Form * *-->
                            <!-- * * * * * * * * * * * * * * *-->
                            <!-- This form is pre-integrated with SB Forms.-->
                            <!-- To make this form functional, sign up at-->
                            <!-- https://startbootstrap.com/solution/contact-forms-->
                            <!-- to get an API token!-->
                            <form class="form-subscribe" id="contactForm" data-sb-form-api-token="API_TOKEN">
                                <!-- Email address input-->
                                <!-- Submit success message-->
                                <!---->
                                <!-- This is what your users will see when the form-->
                                <!-- has successfully submitted-->
                                <div class="d-none" id="submitSuccessMessage">
                                    <div class="text-center mb-3">
                                        <div class="fw-bolder">Form submission successful!</div>
                                        <p>To activate this form, sign up at</p>
                                        <a class="text-white" href="https://startbootstrap.com/solution/contact-forms">https://startbootstrap.com/solution/contact-forms</a>
                                    </div>
                                </div>
                                <!-- Submit error message-->
                                <!---->
                                <!-- This is what your users will see when there is-->
                                <!-- an error submitting the form-->
                                <div class="d-none" id="submitErrorMessage"><div class="text-center text-danger mb-3">Error sending message!</div></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <!-- imagenes-->
        <section>
          {%block imagenes%} 
            
          {%endblock%}
        <!-- posicion de imagen-->
         {%block posicion%}
           <style>
             .posicion-especifica {
                position: absolute;
                top: 100px;
                left: 50px;
             }
            </style>
         {%endblock%}
        <!-- posicion de texto-->

         {%block texto%}

          <style>
             .posicion-especifica {
                position: absolute;
                top: 100px;
                left: 50px;
                }
            </style>
         {%endblock%}

        </section>

                <!-- Footer-->
                <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
        <!-- boton siguiente-->
        
         {%block siguiente%}   {%endblock%}
    </body>
</html>